backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow 
media_folder: "public/assets/stories"
public_folder: "/assets/stories-images"
collections:
  - name: "stories"
    label: "Stories"
    folder: "src/stories"
    create: true
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "shortDesc", widget: "string" }
      - { label: "Badge", name: "badge", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Author Image", name: "authorImage", widget: "image" }
      - { label: "Author Bio", name: "authorBio", widget: "string" }
      - { label: "Time Read", name: "timeRead", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image caption", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }